version: 2
updates:
  # Frontend
  - package-ecosystem: "npm"
    directory: "/frontend/ap-question-generator"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Backend
  - package-ecosystem: maven
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
